### ISSUE TITLE
ModuleNotFoundError: No module named 'halftone'

### ISSUE THREAD

**Issue by mikheys** [RockOfFire/ComfyUI_Comfyroll_CustomNodes#3] opened 2023-08-14 21:31 UTC
The error has reappeared.

Traceback (most recent call last):
  File "H:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\__init__.py", line 1, in <module>
    from .Comfyroll_Nodes import *
  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\Comfyroll_Nodes.py", line 24, in <module>
    from halftone import halftone
ModuleNotFoundError: No module named 'halftone'

**Comment by FoodGoods** [comment] 2023-08-14 21:41
Getting same thing on my end;

0.0 seconds (IMPORT FAILED): :\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes

 Custom Nodes Import Times:

Most of the custom nodes are being imported successfully except for ComfyUI_Comfyroll_CustomNodes which failed due to the missing halftone module.
After installing the missing module, you should attempt to restart ComfyUI or re-import the nodes to see if the issue is resolved.

**Comment by RockOfFire** [comment] 2023-08-14 22:21
Thank you again for catching that!!  I fixed it here.

**Comment by RockOfFire** [comment] 2023-08-14 22:25
All fixed now.  Fixed on CivitAI as well

**Closed** 2023-08-25 08:15 UTC
